// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/14/2025, 2:07:27 PM
const configMerger = require("/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-web-3-1/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-web-3-1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-web-3-1/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-web-3-1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-web-3-1/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-web-3-1/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-web-3-1/plugins/**/*.{js,ts,mjs}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-web-3-1/composables/**/*.{js,ts,mjs}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-web-3-1/utils/**/*.{js,ts,mjs}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-web-3-1/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-web-3-1/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-web-3-1/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["23"] = "/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-web-3-1/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})()
